language: python
python:
- '3.7'
install:
- pip install -r requirements.txt coveralls
- pip install awscli
script:
- aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
- aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
- aws configure set default.region us-east-1
- python -m pytest -q api/tests/unit --cov=api
after_success: coveralls
