language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt coverage coveralls pytest-cov
# command to run tests
script:
  - pytest --cov=api api/tests

after_success: coveralls