language: python
python:
- '3.7'
#branches:
  #only:
    #- master
install:
  - pip install -r requirements.txt coverage coveralls pytest-cov
script:
  - pytest --cov=api api/tests/unit

after_success: coveralls