language: python
python:
- '3.7'
#branches:
  #only:
    #- master
install:
  - pip install -r requirements.txt coveralls 
script:
  - python -m pytest -q api/tests/unit --cov=api

after_success: coveralls
