# serverless.yml
org: photonadmin 
app: photonranch

service: photonranch-api

package:
  exclude:
    - venv/**
    - node_modules/**

plugins:
  - serverless-python-requirements
  #- serverless-dynamodb-pitr
  - serverless-domain-manager

custom:

  # This is the 'variable' for the customDomain.basePath value, based on the stage.
  # Run as `sls deploy --stage <stage_name>`
  stage:
    dev: api
    test: test

  # Make sure to first run 'serverless create_domain'
  customDomain:
    domainName: 'api.photonranch.org'
    basePath: ${self:custom.stage.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.7
  region: us-east-1
  environment: 
    AUTH0_CLIENT_ID: ${file(./secrets.json):AUTH0_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${file(./public_key)}

  iamRoleStatements:
    - Effect: Allow 
      Action: 
        - s3:GetObject
        - s3:PutObject
        - s3:ListBucket
        - s3:ListBucketVersions
      Resource: 
        - "arn:aws:s3:::photonranch-001/*"
        - "arn:aws:s3:::photonranch-001"

    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/*"

    - Effect: Allow 
      Action: 
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:Scan"
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:*"

    - Effect: Allow
      Action:
        - sqs:*
      Resource: arn:aws:sqs:*:*:*

resources: # CloudFormation template syntax from here on.
  Resources:

    # Configure API gateway "Gateway Responses" to work with CORS restrictions
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Access-Control-Allow-Origin'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,Access-Control-Allow-Origin'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

functions:
  authorizerFunc: 
    handler: authorizer.auth
    cors: true
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping/{pathParam}
          method: post
          authorizer:
            name: authorizerFunc
            type: request
            resultTtlInSeconds: 0 # Don't cache the policy or other tasks will fail!
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
  home:
    handler: api/handler.default
    events:
      - http:
          path: /
          method: get
  upload:
    handler: api/handler.upload
    events:
      - http:
          path: /upload
          method: post
  download:
    handler: api/handler.download
    events:
      - http:
          path: /download
          method: post
          cors: true

  latestImage:
    handler: api/handler.latest_image
    events:
      - http:
          path: /{site}/latest_image
          method: get
          cors: true
  latestKImages:
    handler: api/handler.latest_images
    events:
      - http:
          path: /{site}/latest_images/{k}
          method: get
          cors: true

  getConfig:
    handler: api/handler.get_config
    events:
      - http:
          path: /{site}/config
          method: get
          cors: true
  putConfig:
    handler: api/handler.put_config
    events:
      - http:
          path: /{site}/config
          method: put
          cors: true
  deleteConfig:
    handler: api/handler.delete_config
    events:
      - http:
          path: /{site}/config
          method: delete
          cors: true
  allConfig:
    handler: api/handler.all_config
    events:
      - http:
          path: /all/config
          method: get
          cors: true
  getFitsHeader:
    handler: api/handler.get_fits_header
    events:
      - http:
          path: fitsheader/{baseFilename}
          method: get
          cors: true

  filteredImageQuery:
    handler: api/handler.filtered_image_query
    events:
      - http:
          path: filtered_images
          method: get
          cors: true

# pending deletion
  #getImagesByUser:
    #handler: handler.image_by_user
    #memorySize: 3008
    #timeout: 20
    #events:
      #- http:
          #path: /image_by_user/{user_id}
          #method: get
          #cors:
            #origin: '*'
            #headers:
              #- Content-Type
              #- X-Amz-Date
              #- Authorization
              #- X-Api-Key
              #- X-Amz-Security-Token
              #- X-Amz-User-Agent
              #- Access-Control-Allow-Origin
              #- Access-Control-Allow-Credentials

  getCommand:
    handler: api/handler.get_command
    events:
      - http:
          path: /{site}/{mount}/command
          method: get
          cors: true
  postCommand:
    handler: api/handler.post_command
    events:
      - http:
          path: /{site}/{mount}/command
          method: post
          authorizer:
            name: authorizerFunc
            type: request
            resultTtlInSeconds: 0 # Don't cache the policy or other tasks will fail!
          cors: true
  optionsCommand: # This is to fix CORS issues
    handler: api/handler.options_command
    events:
      - http:
          path: /{site}/{mount}/command
          method: options
          cors: true

  getStatus:
    handler: api/handler.get_status
    events:
      - http:
          path: /{site}/status
          method: get
          cors: true
  putStatus: 
    handler: api/handler.put_status
    events:
      - http:
          path: /{site}/status
          method: put
          cors: true

  exampleQuery: 
    handler: api/weather.exampleQuery
    events:
      - http:
          path: /example-query
          method: post
          cors: true

  weatherGraphQuery: 
    handler: api/weather.weatherGraphQuery
    events:
      - http:
          path: /weather/graph-data
          method: post
          cors: true

  addWeatherStatus:
    handler: api/weather.writeWeather
    events:
      - http:
          path: /weather/write
          method: post
          cors: true

  #testEphem:
    #handler: api/handler.testEphem
    #events:
      #- http:
          #path: /testephem
          #method: post
          #cors: true
  #testSkyField:
    #handler: api/handler.testSkyField
    #events:
      #- http:
          #path: /testskyfield
          #method: post
          #cors: true

  siteEvents:
    handler: api/events_handler.siteevents
    events:
      - http:
          path: /events
          method: get
          cors: true

  legacySiteEvents:
    handler: api/events_handler.legacy_siteevents
    events:
      - http:
          path: /legacy_events
          method: get
          cors: true


  
