#
# Github Actions for Serverless Framework
# Learn more: https://maxkostinevich.com/blog/how-to-deploy-serverless-applications-using-github-actions/
#


name: Deploy Test Stage
on:
  push:
    branches:
      - test-deploy
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:

    - name: Create public_key file
      run: | 
        cat > public_key << EOF
        -----BEGIN CERTIFICATE-----
        ${{ secrets.AUTH0_PUBLIC_KEY }}
        -----END CERTIFICATE-----
        
        EOF
    - name: Create Auth0 secrets file
      run: |
        cat > secrets.json << EOF
        {
          "AUTH0_CLIENT_ID": "${{ secrets.AUTH0_CLIENT_ID }}"
        }
        EOF
    - uses: actions/checkout@master
    - name: npm install
      uses: actions/npm@master
      with:
        args: install
    - name: Serverless
      uses: jackdcasey/github-action@python3.8-nodejs13
      with:
        args: deploy --stage test
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
