name: Deploy Test Stage
on:
  push:
    branches:
      - test-deploy
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1

    - name: Create public_key file
      run: | 
        cat > /home/runner/work/photonranch-api/photonranch-api/public_key << EOF
        -----BEGIN CERTIFICATE-----
        ${{ secrets.AUTH0_PUBLIC_KEY }}
        -----END CERTIFICATE-----
        
        EOF
        
    - name: Create Auth0 secrets file
      run: |
        cat > /home/runner/work/photonranch-api/photonranch-api/secrets.json << EOF
        {
          "AUTH0_CLIENT_ID": "${{ secrets.AUTH0_CLIENT_ID }}"
        }
        EOF

    - name: Create AWS credentials file
      run: |
        cat > ~/.aws/credentials << EOF
        [default]
        aws_access_key_id=${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key=${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
        EOF

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7  # Update with your python version

    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      with:
        args: '--stage test'
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_SECRET_KEY }}
