name: Deploy Test Stage
on:
  push:
    branches:
      - test-deploy
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:

    - name: Create public_key file
      run: | 
        cat > public_key << EOF
        -----BEGIN CERTIFICATE-----
        ${{ secrets.AUTH0_PUBLIC_KEY }}
        -----END CERTIFICATE-----
        
        EOF
    - name: Create Auth0 secrets file
      run: |
        cat > secrets.json << EOF
        {
          "AUTH0_CLIENT_ID": "${{ secrets.AUTH0_CLIENT_ID }}"
        }
        EOF

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7  # Update with your python version

    - name: Serverless Deploy
      uses: dhollerbach/github-action-serverless-with-python-requirements@master
      with:
        args: '--stage test'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.SLS_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SLS_AWS_SECRET_ACCESS_KEY }}
